using IntegrationLib;
using SharedLib;
using System;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.IO;

namespace BaseLmPlugin
{
    [Serializable()]
    public class ProcessLicenseManagerSettings : PropertyChangedNotificator,
     IPluginSettings
    {
        private string executablePath,
            workingDirectory,
            arguments;
        private bool waitForExit = true, hide = false;

        [Display(Order = 0)]
        [Name("Executable path", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_EXECUTABLE_PATH_NAME))]
        [ExtendedDescription("Sets path to executable file to be used", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_EXECUTABLE_PATH_DESCRIPTION))]
        public string ExecutablePath
        {
            get { return executablePath; }
            set
            {
                executablePath = value;
                RaisePropertyChanged("ExecutablePath");
            }
        }

        [Display(Order = 1)]
        [Name("Executable arguments", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_ARGUMENTS_NAME))]
        [ExtendedDescription("Sets executable arguments to be used", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_ARGUMENTS_DESCRIPTION))]
        public string Arguments
        {
            get { return arguments; }
            set
            {
                arguments = value;
                RaisePropertyChanged("Arguments");
            }
        }

        [Display(Order = 3)]
        [Name("Executable arguments", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_WAIT_FOR_EXIT_NAME))]
        [ExtendedDescription("Sets executable arguments to be used", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_WAIT_FOR_EXIT_DESCRIPTION))]
        public bool WaitForExit
        {
            get { return waitForExit; }
            set
            {
                waitForExit = value;
                RaisePropertyChanged("WaitForExit");
            }
        }

        [Display(Order = 2)]
        [Name("Working directory", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_WORKING_DIRECTORY_NAME))]
        [ExtendedDescription("Sets executable working directory", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_WORKING_DIRECTORY_DESCRIPTION))]
        public string WorkingDirectory
        {
            get { return workingDirectory; }
            set
            {
                workingDirectory = value;
                RaisePropertyChanged("WorkingDirectory");
            }
        }

        [Display(Order = 4)]
        [Name("Hide main window", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_HIDE_NAME))]
        [ExtendedDescription("Sets if we should try to start executable file process with its main window hidden", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_HIDE_DESCRIPTION))]
        public bool Hide
        {
            get { return hide; }
            set { hide = value; }
        }

        public Process GetProcess(ProcessLicenseKey key)
        {
            if (key != null)
            {
                var lmProcess = new Process();

                #region Configure Process
                lmProcess.StartInfo.UseShellExecute = false;
                if (Hide)
                {
                    lmProcess.StartInfo.CreateNoWindow = true;
                    lmProcess.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
                }
                #endregion

                #region Fileds
                string processPath = string.Empty,
                    workingDirectory = string.Empty,
                    arguments = string.Empty,
                    keyValue = string.Empty;
                #endregion

                #region Expand Paths
                if (!string.IsNullOrWhiteSpace(ExecutablePath))
                {
                    processPath = Environment.ExpandEnvironmentVariables(ExecutablePath);
                }
                else
                {
                    throw new ArgumentException("Executable path cannot be null.");
                }
                if (!string.IsNullOrWhiteSpace(WorkingDirectory))
                {
                    workingDirectory = Environment.ExpandEnvironmentVariables(WorkingDirectory);
                }
                else
                {
                    workingDirectory = Path.GetDirectoryName(ExecutablePath);
                }
                if (!string.IsNullOrWhiteSpace(key.Value))
                {
                    keyValue = Environment.ExpandEnvironmentVariables(key.Value);
                }
                else
                {
                    throw new ArgumentException("Key value cannot be null.");
                }
                if (!string.IsNullOrWhiteSpace(Arguments))
                {
                    arguments = Environment.ExpandEnvironmentVariables(Arguments);
                    arguments = arguments.Replace("%license%", keyValue);
                }
                #endregion

                #region Assing Values
                lmProcess.StartInfo.EnvironmentVariables.Add("license", keyValue);
                lmProcess.StartInfo.FileName = processPath;
                lmProcess.StartInfo.WorkingDirectory = workingDirectory;
                lmProcess.StartInfo.Arguments = arguments;
                #endregion

                return lmProcess;
            }
            else
            {
                throw new NullReferenceException("License key cannot be null.");
            }
        }
    }
}
