using System;
using System.Diagnostics;
using System.Windows.Controls;
using System.Windows;
using System.ComponentModel.Composition;
using System.IO;
using IntegrationLib;
using SharedLib;
using Gizmo.Shared.Plugins;
using System.ComponentModel.DataAnnotations;

namespace BaseLmPlugin
{
    #region ProcessLicenseManager
    [Export(typeof(IntegrationLib.ILicenseManagerPlugin))]
    [PluginMetadata(
        "Process",
        "1.0.0.0",
        "Manages license keys by passing them to external executables.",
        "BaseLmPlugin;BaseLmPlugin.Resources.Icons.process.png")]
    public class ProcessLicenseManager : ConfigurableLicenseManagerBase
    {
        #region OVERRIDES

        public override IApplicationLicenseKey EditLicense(IApplicationLicenseKey key, ILicenseProfile profile, ref bool additionHandled, Window owner)
        {
            var context = new DialogContext(DialogType.Process, key, profile);
            if (context.Display(owner))
            {
                return context.Key;
            }
            else
            {
                return null;
            }
        }

        public override IApplicationLicenseKey GetLicense(ILicenseProfile profile, ref bool additionHandled, Window owner)
        {
            var context = new DialogContext(DialogType.Process, new ProcessLicenseKey(), profile);
            if (context.Display(owner))
            {
                return context.Key;
            }
            else
            {
                return null;
            }
        }

        public override void Install(IApplicationLicense license, Client.IExecutionContext context, ref bool forceCreation)
        {
            var settings = this.SettingsAs<ProcessLicenseManagerSettings>();
            var process = settings.GetProcess(license.KeyAs<ProcessLicenseKey>());
            process.Start();
            if (settings.WaitForExit)
            {
                process.WaitForExit();
            }
        }

        public override IPluginSettings GetSettingsInstance()
        {
            return new ProcessLicenseManagerSettings();
        }

        public override UserControl GetConfigurationUI()
        {
            return new ProcessLicenseManagerView();
        }

        public override bool CanEdit
        {
            get
            {
                return true;
            }
        }

        #endregion
    }
    #endregion

    #region Settings
    [Serializable()]
    public class ProcessLicenseManagerSettings : PropertyChangedNotificator,
        IPluginSettings
    {
        #region Fileds
        private string executablePath,
            workingDirectory,
            arguments;
        private bool waitForExit = true, hide = false;
        #endregion

        #region Properties


        [Name("Executable path", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_EXECUTABLE_PATH_NAME))]
        [ExtendedDescription("Sets path to executable file to be used", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_EXECUTABLE_PATH_DESCRIPTION))]
        public string ExecutablePath
        {
            get { return this.executablePath; }
            set
            {
                this.executablePath = value;
                this.RaisePropertyChanged("ExecutablePath");
            }
        }

        [Name("Executable arguments", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_ARGUMENTS_NAME))]
        [ExtendedDescription("Sets executable arguments to be used", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_ARGUMENTS_DESCRIPTION))]
        public string Arguments
        {
            get { return this.arguments; }
            set
            {
                this.arguments = value;
                this.RaisePropertyChanged("Arguments");
            }
        }

        [Name("Executable arguments", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_WAIT_FOR_EXIT_NAME))]
        [ExtendedDescription("Sets executable arguments to be used", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_WAIT_FOR_EXIT_DESCRIPTION))]
        public bool WaitForExit
        {
            get { return this.waitForExit; }
            set
            {
                this.waitForExit = value;
                this.RaisePropertyChanged("WaitForExit");
            }
        }


        [Name("Working directory", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_WORKING_DIRECTORY_NAME))]
        [ExtendedDescription("Sets executable working directory", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_WORKING_DIRECTORY_DESCRIPTION))]
        public string WorkingDirectory
        {
            get { return this.workingDirectory; }
            set
            {
                this.workingDirectory = value;
                this.RaisePropertyChanged("WorkingDirectory");
            }
        }

        [Name("Hide main window", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_HIDE_NAME))]
        [ExtendedDescription("Sets if we should try to start executable file process with its main window hidden", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_OPTION_HIDE_DESCRIPTION))]
        public bool Hide
        {
            get { return this.hide; }
            set { this.hide = value; }
        }

        #endregion

        #region Functions
        public Process GetProcess(ProcessLicenseKey key)
        {
            if (key != null)
            {
                var lmProcess = new Process();

                #region Configure Process
                lmProcess.StartInfo.UseShellExecute = false;
                if (this.Hide)
                {
                    lmProcess.StartInfo.CreateNoWindow = true;
                    lmProcess.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
                }
                #endregion

                #region Fileds
                string processPath = String.Empty,
                    workingDirectory = String.Empty,
                    arguments = String.Empty,
                    keyValue = String.Empty;
                #endregion

                #region Expand Paths
                if (!String.IsNullOrWhiteSpace(this.ExecutablePath))
                {
                    processPath = Environment.ExpandEnvironmentVariables(this.ExecutablePath);
                }
                else
                {
                    throw new ArgumentException("Executable path cannot be null.");
                }
                if (!String.IsNullOrWhiteSpace(this.WorkingDirectory))
                {
                    workingDirectory = Environment.ExpandEnvironmentVariables(this.WorkingDirectory);
                }
                else
                {
                    workingDirectory = Path.GetDirectoryName(this.ExecutablePath);
                }
                if (!String.IsNullOrWhiteSpace(key.Value))
                {
                    keyValue = Environment.ExpandEnvironmentVariables(key.Value);
                }
                else
                {
                    throw new ArgumentException("Key value cannot be null.");
                }
                if (!String.IsNullOrWhiteSpace(this.Arguments))
                {
                    arguments = Environment.ExpandEnvironmentVariables(this.Arguments);
                    arguments = arguments.Replace("%license%", keyValue);
                }
                #endregion

                #region Assing Values
                lmProcess.StartInfo.EnvironmentVariables.Add("license", keyValue);
                lmProcess.StartInfo.FileName = processPath;
                lmProcess.StartInfo.WorkingDirectory = workingDirectory;
                lmProcess.StartInfo.Arguments = arguments;
                #endregion

                return lmProcess;
            }
            else
            {
                throw new NullReferenceException("License key cannot be null.");
            }
        }
        #endregion
    }
    #endregion

    [PartNotDiscoverable()]
    [Name("Process license manager", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_NAME))]
    [ExtendedDescription("Manages license keys by passing them to external executables", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_DESCRIPTION))]
    [LicenseManagerPlugin("BaseLmPlugin.ProcessLicenseManager", ConfigurationType = typeof(ProcessLicenseManagerSettings), KeyType = typeof(ProcessLicenseKey))]
    public sealed class ProcessLicenseManagerProxy : IPlugin
    {
    }
}
