using Gizmo.Shared.Plugins;
using IntegrationLib;
using System.ComponentModel.Composition;
using System.ComponentModel.DataAnnotations;
using System.Runtime.InteropServices;

namespace BaseLmPlugin
{
    [Export(typeof(ILicenseManagerPlugin))]
    [Guid(Identifiers.Process)]
    [PluginMetadata(
        "Process",
        "1.0.0.0",
        "Manages license keys by passing them to external executables.",
        "BaseLmPlugin;BaseLmPlugin.Resources.Icons.process.png")]
    [Name("Process license manager", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_NAME))]
    [ExtendedDescription("Manages license keys by passing them to external executables", nameof(Autogenerated.Resources.PROCESS_LICENSE_MANAGER_DESCRIPTION))]
    [LicenseManagerPlugin(ConfigurationType = typeof(ProcessLicenseManagerSettings), KeyType = typeof(ProcessLicenseKey))]
    public class ProcessLicenseManager : ConfigurableLicenseManagerBase
    {
        public override void Install(IApplicationLicense license, Client.IExecutionContext context, ref bool forceCreation)
        {
            var settings = SettingsAs<ProcessLicenseManagerSettings>();
            var process = settings.GetProcess(license.KeyAs<ProcessLicenseKey>());
            process.Start();
            if (settings.WaitForExit)
            {
                process.WaitForExit();
            }
        }

        public override IPluginSettings GetSettingsInstance()
        {
            return new ProcessLicenseManagerSettings();
        }
    }
}
