using IntegrationLib;
using Microsoft.Win32;
using SharedLib;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;

namespace BaseLmPlugin
{
    [Serializable()]
    public class RegistryLicenseManagerSettings : PropertyChangedNotificator, IPluginSettings
    {
        private string registryPath;
        private RegistryHive registryHive = RegistryHive.CurrentUser;
        private RegistryValueKind valueKind = RegistryValueKind.String;

        /// <summary>
        /// Gets or sets hive of this registry key.
        /// </summary>
        [Display(Order = 0)]
        [Name("", nameof(Autogenerated.Resources.LICENSE_MANAGER_SETTINGS_REGISTRY_HIVE_NAME))]
        [ExtendedDescription("", nameof(Autogenerated.Resources.LICENSE_MANAGER_SETTINGS_REGISTRY_HIVE_DESCRIPTION))]
        [DefaultValue(RegistryHive.CurrentUser)]
        public RegistryHive Hive
        {
            get { return registryHive; }
            set
            {
                registryHive = value;
                RaisePropertyChanged("Hive");
            }
        }

        /// <summary>
        /// Gets or sets path to the registry key.
        /// </summary>
        [Display(Order = 1)]
        [Name("", nameof(Autogenerated.Resources.LICENSE_MANAGER_SETTINGS_REGISTRY_PATH_NAME))]
        [ExtendedDescription("", nameof(Autogenerated.Resources.LICENSE_MANAGER_SETTINGS_REGISTRY_PATH_DESCRIPTION))]
        public string RegistryPath
        {
            get { return registryPath; }
            set
            {
                registryPath = value;
                RaisePropertyChanged("RegistryPath");
            }
        }

        /// <summary>
        /// Gets or sets the value kind of registry key.
        /// </summary>
        [Display(Order = 2)]
        [Name("", nameof(Autogenerated.Resources.LICENSE_MANAGER_SETTINGS_REGISTRY_VALUE_KIND_NAME))]
        [ExtendedDescription("", nameof(Autogenerated.Resources.LICENSE_MANAGER_SETTINGS_REGISTRY_VALUE_KIND_DESCRIPTION))]
        [DefaultValue(RegistryValueKind.DWord)]
        public RegistryValueKind ValueKind
        {
            get { return valueKind; }
            set
            {
                valueKind = value;
                RaisePropertyChanged("ValueKind");
            }
        }

        /// <summary>
        /// Gets normalized registry path.
        /// </summary>
        public string KeyPath
        {
            get
            {
                if (!string.IsNullOrWhiteSpace(RegistryPath))
                {
                    string normalizedPath = RegistryPath;
                    if (normalizedPath.StartsWith(@"\"))
                    {
                        normalizedPath = normalizedPath.Remove(0, 1);
                    }
                    if (!normalizedPath.EndsWith(@"\"))
                    {
                        return Path.GetDirectoryName(normalizedPath);
                    }
                    else
                    {
                        return normalizedPath;
                    }
                }
                else
                {
                    return string.Empty;
                }
            }
        }

        /// <summary>
        /// Gets the value name.
        /// <remarks>Returns empty string if no value name is present in the registry path.</remarks>
        /// </summary>
        public string ValueName
        {
            get
            {
                if (!string.IsNullOrWhiteSpace(RegistryPath))
                {
                    if (!RegistryPath.EndsWith(@"\"))
                    {
                        return Path.GetFileName(RegistryPath);
                    }
                    else
                    {
                        return string.Empty;
                    }
                }
                else
                {
                    return string.Empty;
                }
            }
        }
    }
}
