//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseLmPlugin.Autogenerated {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseLmPlugin.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account id.
        /// </summary>
        internal static string LICENSE_KEY_ACCOUNT_ID_NAME {
            get {
                return ResourceManager.GetString("LICENSE_KEY_ACCOUNT_ID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LICENSE_KEY_PASSWORD_NAME {
            get {
                return ResourceManager.GetString("LICENSE_KEY_PASSWORD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LICENSE_KEY_USER_NAME_NAME {
            get {
                return ResourceManager.GetString("LICENSE_KEY_USER_NAME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies registry hive.
        /// </summary>
        internal static string LICENSE_MANAGER_SETTINGS_REGISTRY_HIVE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_MANAGER_SETTINGS_REGISTRY_HIVE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry hive.
        /// </summary>
        internal static string LICENSE_MANAGER_SETTINGS_REGISTRY_HIVE_NAME {
            get {
                return ResourceManager.GetString("LICENSE_MANAGER_SETTINGS_REGISTRY_HIVE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies registry path.
        /// </summary>
        internal static string LICENSE_MANAGER_SETTINGS_REGISTRY_PATH_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_MANAGER_SETTINGS_REGISTRY_PATH_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry path.
        /// </summary>
        internal static string LICENSE_MANAGER_SETTINGS_REGISTRY_PATH_NAME {
            get {
                return ResourceManager.GetString("LICENSE_MANAGER_SETTINGS_REGISTRY_PATH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies value kind.
        /// </summary>
        internal static string LICENSE_MANAGER_SETTINGS_REGISTRY_VALUE_KIND_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_MANAGER_SETTINGS_REGISTRY_VALUE_KIND_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value kind.
        /// </summary>
        internal static string LICENSE_MANAGER_SETTINGS_REGISTRY_VALUE_KIND_NAME {
            get {
                return ResourceManager.GetString("LICENSE_MANAGER_SETTINGS_REGISTRY_VALUE_KIND_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolon-separated list of process names (or full executable names) to ignore when evaluating the process tree. Ignored processes won’t keep the session alive and won’t affect exit detection..
        /// </summary>
        internal static string LICENSE_MANAGER_SETTINGS_STEAM_CHILD_IGNORE_LIST_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_MANAGER_SETTINGS_STEAM_CHILD_IGNORE_LIST_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored processes in tree.
        /// </summary>
        internal static string LICENSE_MANAGER_SETTINGS_STEAM_CHILD_IGNORE_LIST_NAME {
            get {
                return ResourceManager.GetString("LICENSE_MANAGER_SETTINGS_STEAM_CHILD_IGNORE_LIST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to wait before ending the session after the tracked process tree is considered exited. This helps avoid false exits during quick restarts or launcher handoffs..
        /// </summary>
        internal static string LICENSE_MANAGER_SETTINGS_STEAM_CHILD_WAIT_TIMEOUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_MANAGER_SETTINGS_STEAM_CHILD_WAIT_TIMEOUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grace period after tree exit.
        /// </summary>
        internal static string LICENSE_MANAGER_SETTINGS_STEAM_CHILD_WAIT_TIMEOUT_NAME {
            get {
                return ResourceManager.GetString("LICENSE_MANAGER_SETTINGS_STEAM_CHILD_WAIT_TIMEOUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables termination of child processes.
        /// </summary>
        internal static string LICENSE_MANAGER_SETTINGS_STEAM_TERMINATE_CHILD_ON_EXIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_MANAGER_SETTINGS_STEAM_TERMINATE_CHILD_ON_EXIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End session when process tree exits.
        /// </summary>
        internal static string LICENSE_MANAGER_SETTINGS_STEAM_TERMINATE_CHILD_ON_EXIT_NAME {
            get {
                return ResourceManager.GetString("LICENSE_MANAGER_SETTINGS_STEAM_TERMINATE_CHILD_ON_EXIT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manages license keys by passing them to external executables.
        /// </summary>
        internal static string PROCESS_LICENSE_MANAGER_DESCRIPTION {
            get {
                return ResourceManager.GetString("PROCESS_LICENSE_MANAGER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process license manager.
        /// </summary>
        internal static string PROCESS_LICENSE_MANAGER_NAME {
            get {
                return ResourceManager.GetString("PROCESS_LICENSE_MANAGER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets executable arguments to be used.
        /// </summary>
        internal static string PROCESS_LICENSE_MANAGER_OPTION_ARGUMENTS_DESCRIPTION {
            get {
                return ResourceManager.GetString("PROCESS_LICENSE_MANAGER_OPTION_ARGUMENTS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable arguments.
        /// </summary>
        internal static string PROCESS_LICENSE_MANAGER_OPTION_ARGUMENTS_NAME {
            get {
                return ResourceManager.GetString("PROCESS_LICENSE_MANAGER_OPTION_ARGUMENTS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets path to executable file to be used.
        /// </summary>
        internal static string PROCESS_LICENSE_MANAGER_OPTION_EXECUTABLE_PATH_DESCRIPTION {
            get {
                return ResourceManager.GetString("PROCESS_LICENSE_MANAGER_OPTION_EXECUTABLE_PATH_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable path.
        /// </summary>
        internal static string PROCESS_LICENSE_MANAGER_OPTION_EXECUTABLE_PATH_NAME {
            get {
                return ResourceManager.GetString("PROCESS_LICENSE_MANAGER_OPTION_EXECUTABLE_PATH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets if we should try to start executable file process with its main window hidden.
        /// </summary>
        internal static string PROCESS_LICENSE_MANAGER_OPTION_HIDE_DESCRIPTION {
            get {
                return ResourceManager.GetString("PROCESS_LICENSE_MANAGER_OPTION_HIDE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide main window.
        /// </summary>
        internal static string PROCESS_LICENSE_MANAGER_OPTION_HIDE_NAME {
            get {
                return ResourceManager.GetString("PROCESS_LICENSE_MANAGER_OPTION_HIDE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets if we should wait for the executable process to exit.
        /// </summary>
        internal static string PROCESS_LICENSE_MANAGER_OPTION_WAIT_FOR_EXIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("PROCESS_LICENSE_MANAGER_OPTION_WAIT_FOR_EXIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for exit.
        /// </summary>
        internal static string PROCESS_LICENSE_MANAGER_OPTION_WAIT_FOR_EXIT_NAME {
            get {
                return ResourceManager.GetString("PROCESS_LICENSE_MANAGER_OPTION_WAIT_FOR_EXIT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets executable working directory.
        /// </summary>
        internal static string PROCESS_LICENSE_MANAGER_OPTION_WORKING_DIRECTORY_DESCRIPTION {
            get {
                return ResourceManager.GetString("PROCESS_LICENSE_MANAGER_OPTION_WORKING_DIRECTORY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory.
        /// </summary>
        internal static string PROCESS_LICENSE_MANAGER_OPTION_WORKING_DIRECTORY_NAME {
            get {
                return ResourceManager.GetString("PROCESS_LICENSE_MANAGER_OPTION_WORKING_DIRECTORY_NAME", resourceCulture);
            }
        }
    }
}
