using IntegrationLib;
using System;
using System.ComponentModel.DataAnnotations;

namespace BaseLmPlugin
{
    [Serializable()]
    public class SteamLicenseKey : ApplicationLicenseKeyBase
    {
        private string
            username,
            password,
            accountId;

        /// <summary>
        /// Gets or sets licenses username.
        /// </summary>
        [Name("Username", nameof(Autogenerated.Resources.LICENSE_KEY_USER_NAME_NAME))]
        public string Username
        {
            get { return this.username; }
            set
            {
                username = value;
                RaisePropertyChanged("Username");
            }
        }

        /// <summary>
        /// Gets or sets license password.
        /// </summary>
        [Name("Password", nameof(Autogenerated.Resources.LICENSE_KEY_PASSWORD_NAME))]
        public string Password
        {
            get { return password; }
            set
            {
                password = value;
                RaisePropertyChanged("Password");
            }
        }

        /// <summary>
        /// Gets or sets account id.
        /// </summary>
        [Name("Account Id", nameof(Autogenerated.Resources.LICENSE_KEY_ACCOUNT_ID_NAME))]
        public string AccountId
        {
            get { return accountId; }
            set
            {
                accountId = value;
                RaisePropertyChanged("AccountId");
            }
        }

        /// <summary>
        /// Gets if license is valid.
        /// </summary>
        public override bool IsValid
        {
            get
            {
                //both username and password must not be null or empty in order to be considered valid
                return !string.IsNullOrWhiteSpace(Username) && !string.IsNullOrWhiteSpace(Password);
            }
        }

        /// <summary>
        /// Gets license literal string representation.
        /// </summary>
        public override string KeyString
        {
            get
            {
                //by default only username will be shown as key representation.
                return Username ?? "Invalid key";
            }
        }

        public override string ToString()
        {
            return this.KeyString;
        }

        // override in order to hide (make no discoverable) the Value property from base class        
        public override string Value { get => base.Value; set => base.Value = value; }
    }
}
